/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Contact {
  'displayName' : string,
  'owner' : Principal,
  'contactLabel' : string,
  'phoneNumber' : string,
}
export interface Conversation {
  'id' : string,
  'members' : Array<Principal>,
  'isGroup' : boolean,
  'name' : string,
  'createdAt' : bigint,
  'description' : string,
}
export interface ConversationSummary {
  'lastMessage' : [] | [Message],
  'conversation' : Conversation,
  'unreadCount' : bigint,
}
export type ExternalBlob = Uint8Array;
export type Gender = { 'other' : null } |
  { 'female' : null } |
  { 'male' : null };
export type MediaType = { 'gif' : null } |
  { 'audio' : null } |
  { 'video' : null } |
  { 'voice' : null } |
  { 'text' : null } |
  { 'emoji' : null } |
  { 'image' : null } |
  { 'sticker' : null };
export interface Message {
  'id' : string,
  'media' : [] | [ExternalBlob],
  'status' : MessageStatus,
  'content' : string,
  'sender' : Principal,
  'conversationId' : string,
  'timestamp' : bigint,
  'mediaType' : MediaType,
}
export type MessageStatus = { 'deleted' : null } |
  { 'read' : null } |
  { 'sent' : null } |
  { 'received' : null };
export interface Reaction {
  'id' : string,
  'messageId' : string,
  'userId' : Principal,
  'emoji' : string,
  'timestamp' : bigint,
}
export interface UserProfile {
  'id' : Principal,
  'displayName' : string,
  'dateOfBirth' : bigint,
  'createdAt' : bigint,
  'address' : string,
  'gender' : Gender,
  'phoneNumber' : string,
  'profilePicture' : [] | [ExternalBlob],
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addContact' : ActorMethod<[string, string], undefined>,
  'addMember' : ActorMethod<[string, Principal], undefined>,
  'addReaction' : ActorMethod<[string, string], string>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createConversation' : ActorMethod<
    [string, string, boolean, Array<Principal>],
    string
  >,
  'deleteMessage' : ActorMethod<[string], undefined>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getContacts' : ActorMethod<[], Array<Contact>>,
  'getConversation' : ActorMethod<[string], Conversation>,
  'getConversations' : ActorMethod<[], Array<ConversationSummary>>,
  'getMessages' : ActorMethod<[string, bigint, bigint], Array<Message>>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getReactions' : ActorMethod<[string], Array<Reaction>>,
  'getTotalUnread' : ActorMethod<[], bigint>,
  'getUnreadCounts' : ActorMethod<[], Array<[string, bigint]>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'leaveConversation' : ActorMethod<[string], undefined>,
  'markConversationAsRead' : ActorMethod<[string], undefined>,
  'registerUser' : ActorMethod<
    [string, string, Gender, string, bigint, [] | [ExternalBlob]],
    undefined
  >,
  'removeContact' : ActorMethod<[string], undefined>,
  'removeMember' : ActorMethod<[string, Principal], undefined>,
  'removeReaction' : ActorMethod<[string], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchUsersByDisplayName' : ActorMethod<[string], Array<UserProfile>>,
  'searchUsersByPhoneNumber' : ActorMethod<[string], Array<UserProfile>>,
  'sendMessage' : ActorMethod<
    [string, string, MediaType, [] | [ExternalBlob]],
    string
  >,
  'updateMessageStatus' : ActorMethod<[string, MessageStatus], undefined>,
  'updateUser' : ActorMethod<
    [string, Gender, string, [] | [ExternalBlob]],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];