/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Gender = IDL.Variant({
  'other' : IDL.Null,
  'female' : IDL.Null,
  'male' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const UserProfile = IDL.Record({
  'id' : IDL.Principal,
  'displayName' : IDL.Text,
  'dateOfBirth' : IDL.Int,
  'createdAt' : IDL.Int,
  'address' : IDL.Text,
  'gender' : Gender,
  'phoneNumber' : IDL.Text,
  'profilePicture' : IDL.Opt(ExternalBlob),
});
export const Contact = IDL.Record({
  'displayName' : IDL.Text,
  'owner' : IDL.Principal,
  'contactLabel' : IDL.Text,
  'phoneNumber' : IDL.Text,
});
export const Conversation = IDL.Record({
  'id' : IDL.Text,
  'members' : IDL.Vec(IDL.Principal),
  'isGroup' : IDL.Bool,
  'name' : IDL.Text,
  'createdAt' : IDL.Int,
  'description' : IDL.Text,
});
export const MessageStatus = IDL.Variant({
  'deleted' : IDL.Null,
  'read' : IDL.Null,
  'sent' : IDL.Null,
  'received' : IDL.Null,
});
export const MediaType = IDL.Variant({
  'gif' : IDL.Null,
  'audio' : IDL.Null,
  'video' : IDL.Null,
  'voice' : IDL.Null,
  'text' : IDL.Null,
  'emoji' : IDL.Null,
  'image' : IDL.Null,
  'sticker' : IDL.Null,
});
export const Message = IDL.Record({
  'id' : IDL.Text,
  'media' : IDL.Opt(ExternalBlob),
  'status' : MessageStatus,
  'content' : IDL.Text,
  'sender' : IDL.Principal,
  'conversationId' : IDL.Text,
  'timestamp' : IDL.Int,
  'mediaType' : MediaType,
});
export const ConversationSummary = IDL.Record({
  'lastMessage' : IDL.Opt(Message),
  'conversation' : Conversation,
  'unreadCount' : IDL.Nat,
});
export const Reaction = IDL.Record({
  'id' : IDL.Text,
  'messageId' : IDL.Text,
  'userId' : IDL.Principal,
  'emoji' : IDL.Text,
  'timestamp' : IDL.Int,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'addMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'addReaction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createConversation' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Principal)],
      [IDL.Text],
      [],
    ),
  'deleteMessage' : IDL.Func([IDL.Text], [], []),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getConversation' : IDL.Func([IDL.Text], [Conversation], ['query']),
  'getConversations' : IDL.Func([], [IDL.Vec(ConversationSummary)], ['query']),
  'getMessages' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Vec(Message)],
      ['query'],
    ),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getReactions' : IDL.Func([IDL.Text], [IDL.Vec(Reaction)], ['query']),
  'getTotalUnread' : IDL.Func([], [IDL.Nat], ['query']),
  'getUnreadCounts' : IDL.Func(
      [],
      [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'leaveConversation' : IDL.Func([IDL.Text], [], []),
  'markConversationAsRead' : IDL.Func([IDL.Text], [], []),
  'registerUser' : IDL.Func(
      [IDL.Text, IDL.Text, Gender, IDL.Text, IDL.Int, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
  'removeContact' : IDL.Func([IDL.Text], [], []),
  'removeMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
  'removeReaction' : IDL.Func([IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchUsersByDisplayName' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'searchUsersByPhoneNumber' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'sendMessage' : IDL.Func(
      [IDL.Text, IDL.Text, MediaType, IDL.Opt(ExternalBlob)],
      [IDL.Text],
      [],
    ),
  'updateMessageStatus' : IDL.Func([IDL.Text, MessageStatus], [], []),
  'updateUser' : IDL.Func(
      [IDL.Text, Gender, IDL.Text, IDL.Opt(ExternalBlob)],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Gender = IDL.Variant({
    'other' : IDL.Null,
    'female' : IDL.Null,
    'male' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const UserProfile = IDL.Record({
    'id' : IDL.Principal,
    'displayName' : IDL.Text,
    'dateOfBirth' : IDL.Int,
    'createdAt' : IDL.Int,
    'address' : IDL.Text,
    'gender' : Gender,
    'phoneNumber' : IDL.Text,
    'profilePicture' : IDL.Opt(ExternalBlob),
  });
  const Contact = IDL.Record({
    'displayName' : IDL.Text,
    'owner' : IDL.Principal,
    'contactLabel' : IDL.Text,
    'phoneNumber' : IDL.Text,
  });
  const Conversation = IDL.Record({
    'id' : IDL.Text,
    'members' : IDL.Vec(IDL.Principal),
    'isGroup' : IDL.Bool,
    'name' : IDL.Text,
    'createdAt' : IDL.Int,
    'description' : IDL.Text,
  });
  const MessageStatus = IDL.Variant({
    'deleted' : IDL.Null,
    'read' : IDL.Null,
    'sent' : IDL.Null,
    'received' : IDL.Null,
  });
  const MediaType = IDL.Variant({
    'gif' : IDL.Null,
    'audio' : IDL.Null,
    'video' : IDL.Null,
    'voice' : IDL.Null,
    'text' : IDL.Null,
    'emoji' : IDL.Null,
    'image' : IDL.Null,
    'sticker' : IDL.Null,
  });
  const Message = IDL.Record({
    'id' : IDL.Text,
    'media' : IDL.Opt(ExternalBlob),
    'status' : MessageStatus,
    'content' : IDL.Text,
    'sender' : IDL.Principal,
    'conversationId' : IDL.Text,
    'timestamp' : IDL.Int,
    'mediaType' : MediaType,
  });
  const ConversationSummary = IDL.Record({
    'lastMessage' : IDL.Opt(Message),
    'conversation' : Conversation,
    'unreadCount' : IDL.Nat,
  });
  const Reaction = IDL.Record({
    'id' : IDL.Text,
    'messageId' : IDL.Text,
    'userId' : IDL.Principal,
    'emoji' : IDL.Text,
    'timestamp' : IDL.Int,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addContact' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'addMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'addReaction' : IDL.Func([IDL.Text, IDL.Text], [IDL.Text], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createConversation' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Bool, IDL.Vec(IDL.Principal)],
        [IDL.Text],
        [],
      ),
    'deleteMessage' : IDL.Func([IDL.Text], [], []),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getConversation' : IDL.Func([IDL.Text], [Conversation], ['query']),
    'getConversations' : IDL.Func(
        [],
        [IDL.Vec(ConversationSummary)],
        ['query'],
      ),
    'getMessages' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Vec(Message)],
        ['query'],
      ),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getReactions' : IDL.Func([IDL.Text], [IDL.Vec(Reaction)], ['query']),
    'getTotalUnread' : IDL.Func([], [IDL.Nat], ['query']),
    'getUnreadCounts' : IDL.Func(
        [],
        [IDL.Vec(IDL.Tuple(IDL.Text, IDL.Nat))],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'leaveConversation' : IDL.Func([IDL.Text], [], []),
    'markConversationAsRead' : IDL.Func([IDL.Text], [], []),
    'registerUser' : IDL.Func(
        [IDL.Text, IDL.Text, Gender, IDL.Text, IDL.Int, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'removeContact' : IDL.Func([IDL.Text], [], []),
    'removeMember' : IDL.Func([IDL.Text, IDL.Principal], [], []),
    'removeReaction' : IDL.Func([IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchUsersByDisplayName' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'searchUsersByPhoneNumber' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'sendMessage' : IDL.Func(
        [IDL.Text, IDL.Text, MediaType, IDL.Opt(ExternalBlob)],
        [IDL.Text],
        [],
      ),
    'updateMessageStatus' : IDL.Func([IDL.Text, MessageStatus], [], []),
    'updateUser' : IDL.Func(
        [IDL.Text, Gender, IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };