/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface UserProfile {
    id: Principal;
    displayName: string;
    dateOfBirth: bigint;
    createdAt: bigint;
    address: string;
    gender: Gender;
    phoneNumber: string;
    profilePicture?: ExternalBlob;
}
export interface Reaction {
    id: string;
    messageId: string;
    userId: Principal;
    emoji: string;
    timestamp: bigint;
}
export interface Contact {
    displayName: string;
    owner: Principal;
    contactLabel: string;
    phoneNumber: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Message {
    id: string;
    media?: ExternalBlob;
    status: MessageStatus;
    content: string;
    sender: Principal;
    conversationId: string;
    timestamp: bigint;
    mediaType: MediaType;
}
export interface Conversation {
    id: string;
    members: Array<Principal>;
    isGroup: boolean;
    name: string;
    createdAt: bigint;
    description: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export interface ConversationSummary {
    lastMessage?: Message;
    conversation: Conversation;
    unreadCount: bigint;
}
export enum Gender {
    other = "other",
    female = "female",
    male = "male"
}
export enum MediaType {
    gif = "gif",
    audio = "audio",
    video = "video",
    voice = "voice",
    text = "text",
    emoji = "emoji",
    image = "image",
    sticker = "sticker"
}
export enum MessageStatus {
    deleted = "deleted",
    read = "read",
    sent = "sent",
    received = "received"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addContact(phoneNumber: string, contactLabel: string): Promise<void>;
    addMember(conversationId: string, member: Principal): Promise<void>;
    addReaction(messageId: string, emoji: string): Promise<string>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createConversation(name: string, description: string, isGroup: boolean, members: Array<Principal>): Promise<string>;
    deleteMessage(messageId: string): Promise<void>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getContacts(): Promise<Array<Contact>>;
    getConversation(conversationId: string): Promise<Conversation>;
    getConversations(): Promise<Array<ConversationSummary>>;
    getMessages(conversationId: string, limit: bigint, offset: bigint): Promise<Array<Message>>;
    getProfile(): Promise<UserProfile>;
    getReactions(messageId: string): Promise<Array<Reaction>>;
    getTotalUnread(): Promise<bigint>;
    getUnreadCounts(): Promise<Array<[string, bigint]>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    leaveConversation(conversationId: string): Promise<void>;
    markConversationAsRead(conversationId: string): Promise<void>;
    registerUser(phoneNumber: string, displayName: string, gender: Gender, address: string, dateOfBirth: bigint, profilePicture: ExternalBlob | null): Promise<void>;
    removeContact(phoneNumber: string): Promise<void>;
    removeMember(conversationId: string, member: Principal): Promise<void>;
    removeReaction(reactionId: string): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchUsersByDisplayName(name: string): Promise<Array<UserProfile>>;
    searchUsersByPhoneNumber(phoneNumber: string): Promise<Array<UserProfile>>;
    sendMessage(conversationId: string, content: string, mediaType: MediaType, media: ExternalBlob | null): Promise<string>;
    updateMessageStatus(messageId: string, status: MessageStatus): Promise<void>;
    updateUser(displayName: string, gender: Gender, address: string, profilePicture: ExternalBlob | null): Promise<void>;
}
import type { Conversation as _Conversation, ConversationSummary as _ConversationSummary, ExternalBlob as _ExternalBlob, Gender as _Gender, MediaType as _MediaType, Message as _Message, MessageStatus as _MessageStatus, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addContact(arg0: string, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addContact(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addContact(arg0, arg1);
            return result;
        }
    }
    async addMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.addMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMember(arg0, arg1);
            return result;
        }
    }
    async addReaction(arg0: string, arg1: string): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.addReaction(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addReaction(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createConversation(arg0: string, arg1: string, arg2: boolean, arg3: Array<Principal>): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.createConversation(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createConversation(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async deleteMessage(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMessage(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMessage(arg0);
            return result;
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getContacts(): Promise<Array<Contact>> {
        if (this.processError) {
            try {
                const result = await this.actor.getContacts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getContacts();
            return result;
        }
    }
    async getConversation(arg0: string): Promise<Conversation> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversation(arg0);
            return result;
        }
    }
    async getConversations(): Promise<Array<ConversationSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.getConversations();
                return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getConversations();
            return from_candid_vec_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMessages(arg0: string, arg1: bigint, arg2: bigint): Promise<Array<Message>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMessages(arg0, arg1, arg2);
                return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMessages(arg0, arg1, arg2);
            return from_candid_vec_n29(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProfile(): Promise<UserProfile> {
        if (this.processError) {
            try {
                const result = await this.actor.getProfile();
                return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProfile();
            return from_candid_UserProfile_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getReactions(arg0: string): Promise<Array<Reaction>> {
        if (this.processError) {
            try {
                const result = await this.actor.getReactions(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getReactions(arg0);
            return result;
        }
    }
    async getTotalUnread(): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.getTotalUnread();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getTotalUnread();
            return result;
        }
    }
    async getUnreadCounts(): Promise<Array<[string, bigint]>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUnreadCounts();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUnreadCounts();
            return result;
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n10(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async leaveConversation(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.leaveConversation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.leaveConversation(arg0);
            return result;
        }
    }
    async markConversationAsRead(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.markConversationAsRead(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.markConversationAsRead(arg0);
            return result;
        }
    }
    async registerUser(arg0: string, arg1: string, arg2: Gender, arg3: string, arg4: bigint, arg5: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0, arg1, to_candid_Gender_n30(this._uploadFile, this._downloadFile, arg2), arg3, arg4, await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg5));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0, arg1, to_candid_Gender_n30(this._uploadFile, this._downloadFile, arg2), arg3, arg4, await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg5));
            return result;
        }
    }
    async removeContact(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeContact(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeContact(arg0);
            return result;
        }
    }
    async removeMember(arg0: string, arg1: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeMember(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeMember(arg0, arg1);
            return result;
        }
    }
    async removeReaction(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.removeReaction(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.removeReaction(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(await to_candid_UserProfile_n34(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchUsersByDisplayName(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsersByDisplayName(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsersByDisplayName(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchUsersByPhoneNumber(arg0: string): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchUsersByPhoneNumber(arg0);
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchUsersByPhoneNumber(arg0);
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async sendMessage(arg0: string, arg1: string, arg2: MediaType, arg3: ExternalBlob | null): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.sendMessage(arg0, arg1, to_candid_MediaType_n37(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.sendMessage(arg0, arg1, to_candid_MediaType_n37(this._uploadFile, this._downloadFile, arg2), await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
    async updateMessageStatus(arg0: string, arg1: MessageStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMessageStatus(arg0, to_candid_MessageStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMessageStatus(arg0, to_candid_MessageStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUser(arg0: string, arg1: Gender, arg2: string, arg3: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUser(arg0, to_candid_Gender_n30(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg3));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUser(arg0, to_candid_Gender_n30(this._uploadFile, this._downloadFile, arg1), arg2, await to_candid_opt_n32(this._uploadFile, this._downloadFile, arg3));
            return result;
        }
    }
}
async function from_candid_ConversationSummary_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ConversationSummary): Promise<ConversationSummary> {
    return await from_candid_record_n21(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
function from_candid_Gender_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Gender): Gender {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_MediaType_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MediaType): MediaType {
    return from_candid_variant_n28(_uploadFile, _downloadFile, value);
}
function from_candid_MessageStatus_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MessageStatus): MessageStatus {
    return from_candid_variant_n26(_uploadFile, _downloadFile, value);
}
async function from_candid_Message_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Message): Promise<Message> {
    return await from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_UserProfile_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): Promise<UserProfile> {
    return await from_candid_record_n12(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n18(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): Promise<UserProfile | null> {
    return value.length === 0 ? null : await from_candid_UserProfile_n11(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n16(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Message]): Promise<Message | null> {
    return value.length === 0 ? null : await from_candid_Message_n23(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    displayName: string;
    dateOfBirth: bigint;
    createdAt: bigint;
    address: string;
    gender: _Gender;
    phoneNumber: string;
    profilePicture: [] | [_ExternalBlob];
}): Promise<{
    id: Principal;
    displayName: string;
    dateOfBirth: bigint;
    createdAt: bigint;
    address: string;
    gender: Gender;
    phoneNumber: string;
    profilePicture?: ExternalBlob;
}> {
    return {
        id: value.id,
        displayName: value.displayName,
        dateOfBirth: value.dateOfBirth,
        createdAt: value.createdAt,
        address: value.address,
        gender: from_candid_Gender_n13(_uploadFile, _downloadFile, value.gender),
        phoneNumber: value.phoneNumber,
        profilePicture: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.profilePicture))
    };
}
async function from_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    lastMessage: [] | [_Message];
    conversation: _Conversation;
    unreadCount: bigint;
}): Promise<{
    lastMessage?: Message;
    conversation: Conversation;
    unreadCount: bigint;
}> {
    return {
        lastMessage: record_opt_to_undefined(await from_candid_opt_n22(_uploadFile, _downloadFile, value.lastMessage)),
        conversation: value.conversation,
        unreadCount: value.unreadCount
    };
}
async function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    media: [] | [_ExternalBlob];
    status: _MessageStatus;
    content: string;
    sender: Principal;
    conversationId: string;
    timestamp: bigint;
    mediaType: _MediaType;
}): Promise<{
    id: string;
    media?: ExternalBlob;
    status: MessageStatus;
    content: string;
    sender: Principal;
    conversationId: string;
    timestamp: bigint;
    mediaType: MediaType;
}> {
    return {
        id: value.id,
        media: record_opt_to_undefined(await from_candid_opt_n15(_uploadFile, _downloadFile, value.media)),
        status: from_candid_MessageStatus_n25(_uploadFile, _downloadFile, value.status),
        content: value.content,
        sender: value.sender,
        conversationId: value.conversationId,
        timestamp: value.timestamp,
        mediaType: from_candid_MediaType_n27(_uploadFile, _downloadFile, value.mediaType)
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    other: null;
} | {
    female: null;
} | {
    male: null;
}): Gender {
    return "other" in value ? Gender.other : "female" in value ? Gender.female : "male" in value ? Gender.male : value;
}
function from_candid_variant_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    deleted: null;
} | {
    read: null;
} | {
    sent: null;
} | {
    received: null;
}): MessageStatus {
    return "deleted" in value ? MessageStatus.deleted : "read" in value ? MessageStatus.read : "sent" in value ? MessageStatus.sent : "received" in value ? MessageStatus.received : value;
}
function from_candid_variant_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    gif: null;
} | {
    audio: null;
} | {
    video: null;
} | {
    voice: null;
} | {
    text: null;
} | {
    emoji: null;
} | {
    image: null;
} | {
    sticker: null;
}): MediaType {
    return "gif" in value ? MediaType.gif : "audio" in value ? MediaType.audio : "video" in value ? MediaType.video : "voice" in value ? MediaType.voice : "text" in value ? MediaType.text : "emoji" in value ? MediaType.emoji : "image" in value ? MediaType.image : "sticker" in value ? MediaType.sticker : value;
}
async function from_candid_vec_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ConversationSummary>): Promise<Array<ConversationSummary>> {
    return await Promise.all(value.map(async (x)=>await from_candid_ConversationSummary_n20(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Message>): Promise<Array<Message>> {
    return await Promise.all(value.map(async (x)=>await from_candid_Message_n23(_uploadFile, _downloadFile, x)));
}
async function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Promise<Array<UserProfile>> {
    return await Promise.all(value.map(async (x)=>await from_candid_UserProfile_n11(_uploadFile, _downloadFile, x)));
}
async function to_candid_ExternalBlob_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
function to_candid_Gender_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): _Gender {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_MediaType_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): _MediaType {
    return to_candid_variant_n38(_uploadFile, _downloadFile, value);
}
function to_candid_MessageStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageStatus): _MessageStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
async function to_candid_UserProfile_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): Promise<_UserProfile> {
    return await to_candid_record_n35(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
async function to_candid_opt_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: Principal;
    displayName: string;
    dateOfBirth: bigint;
    createdAt: bigint;
    address: string;
    gender: Gender;
    phoneNumber: string;
    profilePicture?: ExternalBlob;
}): Promise<{
    id: Principal;
    displayName: string;
    dateOfBirth: bigint;
    createdAt: bigint;
    address: string;
    gender: _Gender;
    phoneNumber: string;
    profilePicture: [] | [_ExternalBlob];
}> {
    return {
        id: value.id,
        displayName: value.displayName,
        dateOfBirth: value.dateOfBirth,
        createdAt: value.createdAt,
        address: value.address,
        gender: to_candid_Gender_n30(_uploadFile, _downloadFile, value.gender),
        phoneNumber: value.phoneNumber,
        profilePicture: value.profilePicture ? candid_some(await to_candid_ExternalBlob_n33(_uploadFile, _downloadFile, value.profilePicture)) : candid_none()
    };
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Gender): {
    other: null;
} | {
    female: null;
} | {
    male: null;
} {
    return value == Gender.other ? {
        other: null
    } : value == Gender.female ? {
        female: null
    } : value == Gender.male ? {
        male: null
    } : value;
}
function to_candid_variant_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MediaType): {
    gif: null;
} | {
    audio: null;
} | {
    video: null;
} | {
    voice: null;
} | {
    text: null;
} | {
    emoji: null;
} | {
    image: null;
} | {
    sticker: null;
} {
    return value == MediaType.gif ? {
        gif: null
    } : value == MediaType.audio ? {
        audio: null
    } : value == MediaType.video ? {
        video: null
    } : value == MediaType.voice ? {
        voice: null
    } : value == MediaType.text ? {
        text: null
    } : value == MediaType.emoji ? {
        emoji: null
    } : value == MediaType.image ? {
        image: null
    } : value == MediaType.sticker ? {
        sticker: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MessageStatus): {
    deleted: null;
} | {
    read: null;
} | {
    sent: null;
} | {
    received: null;
} {
    return value == MessageStatus.deleted ? {
        deleted: null
    } : value == MessageStatus.read ? {
        read: null
    } : value == MessageStatus.sent ? {
        sent: null
    } : value == MessageStatus.received ? {
        received: null
    } : value;
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
